name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  jobs:
    checks:
      name: Compile Check
      runs-on: ubuntu-22.04
      strategy:
        fail-fast: false
        matrix:
          java: [ 11 ]

      steps:
        - uses: actions/checkout@v4
          with:
            path: activemq-artemis-console-plugin

        - name: Install JDK ${{ matrix.java }}
          uses: actions/setup-java@v4
          with:
            java-version: ${{ matrix.java }}
            distribution: 'temurin'

        - name: Build Artemis  Console Plugin
          run: |
            cd activemq-artemis-console-plugin
            mvn verify
